// Copies ABIs from the Foundry build output into typed TypeScript modules.
// Run `pnpm contracts:build` first, then `pnpm abi:sync`.
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const outDir = join(here, "..", "..", "contracts", "out");
const targetDir = join(here, "..", "src", "abis");

const CONTRACTS = [
  { name: "DeltaMonVault", file: "deltaMonVault.ts", exportName: "deltaMonVaultAbi" },
  { name: "SdMonVault", file: "sdMonVault.ts", exportName: "sdMonVaultAbi" },
  { name: "DeltaVault", file: "deltaVault.ts", exportName: "deltaVaultAbi" },
  {
    name: "DeltaNeutralStrategy",
    file: "deltaNeutralStrategy.ts",
    exportName: "deltaNeutralStrategyAbi",
  },
];

let failed = false;
for (const c of CONTRACTS) {
  const artifact = join(outDir, `${c.name}.sol`, `${c.name}.json`);
  if (!existsSync(artifact)) {
    console.error(`missing artifact ${artifact} (run forge build in packages/contracts)`);
    failed = true;
    continue;
  }
  const { abi } = JSON.parse(readFileSync(artifact, "utf8"));
  const body =
    `// Generated by packages/shared/scripts/sync-abis.mjs from ${c.name}.sol. Do not edit by hand.\n` +
    `export const ${c.exportName} = ${JSON.stringify(abi, null, 2)} as const;\n`;
  writeFileSync(join(targetDir, c.file), body);
  console.log(`wrote ${c.file} (${abi.length} entries)`);
}
process.exit(failed ? 1 : 0);
